# Generated by Django 5.2 on 2025-04-30 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("variable", "0002_alter_variable_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variable",
            name="required",
        ),
    ]
