# Generated by Django 5.2 on 2025-05-06 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variable", "0003_remove_variable_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="variable",
            name="origin",
            field=models.CharField(
                choices=[("original", "Original"), ("derived", "Derived")],
                default="original",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="variable",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_variable",
                to="variable.variable",
            ),
        ),
    ]
