# Generated by Django 5.2 on 2025-05-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variable", "0004_variable_origin_variable_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="variable",
            name="formula",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
