# Generated by Django 5.2 on 2025-05-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="position",
        ),
    ]
