# Generated by Django 5.2 on 2025-05-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_product_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="source_platform",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
