# Generated by Django 5.2 on 2025-05-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_source_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="source_platform",
            field=models.CharField(max_length=255),
        ),
    ]
