# Generated by Django 5.2 on 2025-04-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("element", "0003_alter_element_id"),
        ("trade", "0003_alter_trade_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="elements",
            field=models.ManyToManyField(
                blank=True, related_name="trades", to="element.element"
            ),
        ),
    ]
