# Generated by Django 5.2 on 2025-05-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0004_trade_elements"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="trades/images/"),
        ),
    ]
