# Generated by Django 5.2 on 2025-05-06 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0005_trade_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="origin",
            field=models.CharField(
                choices=[("original", "Original"), ("derived", "Derived")],
                default="original",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_trade",
                to="trade.trade",
            ),
        ),
    ]
