# Generated by Django 5.2 on 2025-04-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscription_plan", "0003_alter_subscriptionplan_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="features",
        ),
    ]
