# Generated by Django 5.2 on 2025-04-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="aihAkMfzsV",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "material_cost_formula",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("material_formula_variables", models.JSONField(blank=True, null=True)),
                (
                    "labor_cost_formula",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("labor_formula_variables", models.JSONField(blank=True, null=True)),
                (
                    "material_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "markup",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Element",
                "verbose_name_plural": "Elements",
                "db_table": "elements",
                "ordering": ["-created_at"],
            },
        ),
    ]
