# Generated by Django 5.2 on 2025-05-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("element", "0003_alter_element_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="elements/images/"
            ),
        ),
    ]
