# Generated by Django 5.2 on 2025-05-06 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("element", "0004_element_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="origin",
            field=models.CharField(
                choices=[("original", "Original"), ("derived", "Derived")],
                default="original",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_element",
                to="element.element",
            ),
        ),
    ]
