# Generated by Django 5.2 on 2025-04-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JWTToken",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="qhFspikzAp",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("access_token", models.CharField(max_length=255, unique=True)),
                ("refresh_token", models.CharField(max_length=255, unique=True)),
                ("access_token_expires_at", models.DateTimeField()),
                ("refresh_token_expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("token_type", models.CharField(default="Bearer", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "JWT Token",
                "verbose_name_plural": "JWT Tokens",
                "db_table": "jwt_tokens",
                "ordering": ["-created_at"],
            },
        ),
    ]
