from .base import *
from config.constants import DATABASES, CORS_CONFIG

DEBUG = False

ALLOWED_HOSTS = ['*']

DATABASES = {
    "default": DATABASES["production"],
}

print("Database Config:", DATABASES)

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = CORS_CONFIG["production"]["ALLOWED_ORIGINS"]
CORS_ALLOW_METHODS = CORS_CONFIG["production"]["ALLOWED_METHODS"]
CORS_ALLOW_HEADERS = CORS_CONFIG["production"]["ALLOWED_HEADERS"]
CORS_EXPOSE_HEADERS = CORS_CONFIG["production"]["EXPOSED_HEADERS"]

SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
