from .base import *
from config.constants import DATABASES, CORS_CONFIG

DEBUG = False

ALLOWED_HOSTS = []

DATABASES = {
    "default": DATABASES["staging"],
}

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = CORS_CONFIG["staging"]["ALLOWED_ORIGINS"]
CORS_ALLOW_METHODS = CORS_CONFIG["staging"]["ALLOWED_METHODS"]
CORS_ALLOW_HEADERS = CORS_CONFIG["staging"]["ALLOWED_HEADERS"]
CORS_EXPOSE_HEADERS = CORS_CONFIG["staging"]["EXPOSED_HEADERS"]
