# Generated by Django 5.2 on 2025-04-29 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VariableType",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="NV2gmRjf8e",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("length", "Length"),
                            ("area", "Area"),
                            ("volume", "Volume"),
                            ("count", "Count"),
                            ("weight", "Weight"),
                            ("custom", "Custom"),
                            ("currency", "Currency"),
                        ],
                        default="custom",
                        max_length=10,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=10, null=True)),
                ("is_built_in", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Variable Type",
                "verbose_name_plural": "Variable Types",
                "db_table": "variable_types",
                "ordering": ["-created_at"],
            },
        ),
    ]
