# Generated by Django 5.2 on 2025-04-29 21:02

import helpers.generate_short_id
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0002_initial"),
        ("trade", "0003_alter_trade_id"),
        ("variable", "0002_alter_variable_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="trade",
        ),
        migrations.RemoveField(
            model_name="template",
            name="variable",
        ),
        migrations.AddField(
            model_name="template",
            name="trades",
            field=models.ManyToManyField(
                blank=True, related_name="templates", to="trade.trade"
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="variables",
            field=models.ManyToManyField(
                blank=True, related_name="templates", to="variable.variable"
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="id",
            field=models.CharField(
                default=helpers.generate_short_id.generate_short_id,
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
