# Generated by Django 5.2 on 2025-04-30 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0003_remove_template_trade_remove_template_variable_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="source_template",
        ),
        migrations.AlterField(
            model_name="template",
            name="source_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_template",
                to="template.template",
            ),
        ),
    ]
