# Generated by Django 5.2 on 2025-05-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0004_remove_template_source_template_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="template",
            old_name="source_id",
            new_name="source",
        ),
        migrations.AddField(
            model_name="template",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="templates/images/"
            ),
        ),
    ]
