# Generated by Django 5.2 on 2025-04-29 21:02

import helpers.generate_short_id
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="id",
            field=models.CharField(
                default=helpers.generate_short_id.generate_short_id,
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
