# Generated by Django 5.2 on 2025-05-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0003_alter_contract_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="client_initials",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="client_signature",
            field=models.ImageField(
                blank=True, null=True, upload_to="signatures/clients/"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="client_signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="contractor_initials",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="contractor_signature",
            field=models.ImageField(
                blank=True, null=True, upload_to="signatures/contractors/"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="contractor_signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
