# Generated by Django 5.2 on 2025-05-06 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "contract",
            "0004_contract_client_initials_contract_client_signature_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="proposal",
        ),
    ]
