# Generated by Django 5.2 on 2025-05-12 17:50

import helpers.generate_short_id
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otp", "0002_alter_otp_options_alter_otp_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="id",
            field=models.CharField(
                default=helpers.generate_short_id.generate_short_id,
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
