# Generated by Django 5.2 on 2025-04-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriptionTransaction",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="tEdUzFyGCA",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("is_successful", models.BooleanField(default=False)),
                ("is_refunded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription Transaction",
                "verbose_name_plural": "Subscription Transactions",
                "db_table": "subscription_transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
