# Generated by Django 5.2 on 2025-04-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposal", "0003_alter_proposal_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="proposals/images/"
            ),
        ),
    ]
