# Generated by Django 5.2 on 2025-05-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proposal", "0004_proposal_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proposal",
            old_name="total_label_cost",
            new_name="total_labor_cost",
        ),
    ]
