# Generated by Django 5.2 on 2025-05-06 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0005_remove_contract_proposal"),
        ("proposal", "0005_rename_total_label_cost_proposal_total_labor_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposals",
                to="contract.contract",
            ),
        ),
    ]
