# Generated by Django 5.2 on 2025-05-04 15:18

import django.db.models.deletion
import helpers.generate_short_id
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agreement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAgreement",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=helpers.generate_short_id.generate_short_id,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_acceptances",
                        to="agreement.agreement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Agreement",
                "verbose_name_plural": "User Agreements",
                "db_table": "user_agreements",
                "ordering": ["-accepted_at"],
            },
        ),
    ]
